version = 5.6.0
archive_dir = /etc/letsencrypt/archive/memutq.ru
cert = /etc/letsencrypt/live/memutq.ru/cert.pem
privkey = /etc/letsencrypt/live/memutq.ru/privkey.pem
chain = /etc/letsencrypt/live/memutq.ru/chain.pem
fullchain = /etc/letsencrypt/live/memutq.ru/fullchain.pem
[renewalparams]
account = c4ce9e3481132d1517c022fa48cd3d9f
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
memutq.ru = /var/www/certbot
www.memutq.ru = /var/www/certbot
